last_updated: '2026-07-04 05:38:22'
locations:
  nav_001:
    fixture: counter
    objects: []
  nav_004:
    fixture: counter
    objects: []
  nav_012:
    fixture: stove
    objects:
    - cup
    - apple
  nav_014:
    fixture: stove
    objects:
    - mug
  nav_033:
    fixture: sink
    objects: []
  nav_044:
    fixture: counter
    objects:
    - pot
    - bowl
  nav_055:
    fixture: sink
    objects: []
  nav_088:
    fixture: island
    objects:
    - sponge
  robot_hand:
    fixture: null
    objects: []
