last_updated: 初始状态
locations:
  nav_002:
    fixture: counter
    objects:
    - sponge
    - ketchup
  nav_004:
    fixture: counter
    objects:
    - plate
  nav_012:
    fixture: stove
    objects:
    - bowl
    - bread
  nav_014:
    fixture: stove
    objects:
    - cheese
  nav_019:
    fixture: counter
    objects:
    - pot
    - cup
  nav_022:
    fixture: counter
    objects:
    - apple
    - mug
  nav_033:
    fixture: sink
    objects: []
  nav_055:
    fixture: sink
    objects: []
  robot_hand:
    fixture: null
    objects: []
