last_updated: 初始状态
locations:
  nav_012:
    fixture: counter
    objects:
    - apple
    - mug
  nav_014:
    fixture: null
    objects:
    - pot
  nav_016:
    fixture: stove
    objects: []
  nav_027:
    fixture: sink
    objects:
    - sponge
  nav_065:
    fixture: null
    objects:
    - bowl
    - cup
  robot_hand:
    fixture: null
    objects: []
