last_updated: 初始状态
locations:
  nav_004:
    fixture: counter
    objects:
    - apple
    - mug
    - pot
  nav_012:
    fixture: stove
    objects: []
  nav_046:
    fixture: sink
    objects: []
  nav_075:
    fixture: null
    objects:
    - sponge
  nav_076:
    fixture: null
    objects:
    - bowl
  nav_094:
    fixture: null
    objects:
    - cup
  robot_hand:
    fixture: null
    objects: []
