waypoints:
- name: nav_012
  pos:
  - 1.525
  - -1.025
  serves:
  - apple
  - counter
  - mug
  yaw_deg: 90.0
- name: nav_014
  pos:
  - 2.525
  - -1.025
  serves:
  - pot
  yaw_deg: 90.0
- name: nav_065
  pos:
  - 4.025
  - -4.025
  serves:
  - cup
  yaw_deg: 90.0
- name: nav_016
  pos:
  - 3.525
  - -1.025
  serves:
  - stove
  yaw_deg: 90.0
- name: nav_027
  pos:
  - 3.025
  - -1.525
  serves:
  - sink
  yaw_deg: 270.0
