waypoints:
- name: nav_002
  pos:
  - 2.225
  - 0.475
  serves:
  - apple
  - counter
  - mug
  - pot
  yaw_deg: -127.0
- name: nav_127
  pos:
  - 4.925
  - -2.825
  serves:
  - bowl
  - cup
  yaw_deg: 172.2
- name: nav_005
  pos:
  - 3.125
  - 0.475
  serves:
  - stove
  yaw_deg: -53.7
- name: nav_065
  pos:
  - 3.125
  - -1.325
  serves:
  - sink
  yaw_deg: -85.6
- name: nav_108
  pos:
  - 1.625
  - -2.225
  serves:
  - sponge
  yaw_deg: -31.3
- name: nav_041
  pos:
  - 1.625
  - -1.025
  serves:
  - counter
  yaw_deg: 83.9
- name: nav_023
  pos:
  - 3.725
  - 0.175
  serves:
  - stove
  yaw_deg: -94.3
- name: nav_084
  pos:
  - 3.125
  - -1.625
  serves:
  - sink
  yaw_deg: -83.7
